version: '2'
services:

  svn:
    build: ../httpd
    image: solsson/svn-httpd
    expose:
      - "80"

  svn_adminrest:
    build: ../httpd
    environment:
      ADMIN_REST_ACCESS: "true"
    expose:
      - "80"

  svn_authz:
    build: ../httpd
    environment:
      ADMIN_REST_ACCESS: "true"
      AUTHZ: "admin"
    expose:
      - "80"

  fpm-svn:
    build: ../rweb/fpm-svn
    image: solsson/fpm-svn
    entrypoint:
      - echo
      - "This was just a build job. Exiting."

  rweb:
    depends_on:
      - fpm-svn
    build: ../rweb/fpm
    image: solsson/rweb-fpm
    expose:
      - "9000"
    links:
      - rweb-httpd:svn

  rweb-httpd:
    depends_on:
      - svn
    build: ../rweb/httpd
    image: solsson/rweb-httpd
    expose:
      - "80"
    environment:
      ADMIN_REST_ACCESS: "true"
      AUTHN: "anon"

  rwebtest:
    build: ./rwebtest
    labels:
      com.yolean.build-contract: "*"
    environment:
      DEBUG: "true"
    links:
      - rweb-httpd:svn

  debian-svnclient:
    build: ../debian-svnclient
    image: solsson/debian-svnclient

  svntest:
    depends_on:
      - debian-svnclient
    build: ./svntest
    labels:
      com.yolean.build-contract: "*"
    links:
      - svn
      - svn_adminrest
