version: '2'
services:

  svn:
    build: ../httpd
    image: solsson/svn-httpd:${PUSH_TAG:-latest}
    expose:
      - "80"

  svn-adminrest:
    build: ../httpd
    environment:
      ADMIN_REST_ACCESS: "true"
    expose:
      - "80"

  svn-authz:
    build: ../httpd
    environment:
      ADMIN_REST_ACCESS: "true"
      AUTHZ: "admrepo"
    expose:
      - "80"

  fpm-svn:
    build:
      context: ../rweb/fpm-svn
      args:
        PUSH_TAG: ${PUSH_TAG:-latest}
    image: solsson/fpm-svn:${PUSH_TAG:-latest}
    entrypoint:
      - echo
      - "This was just a build job. Exiting."

  fpm-rweb:
    depends_on:
      - fpm-svn
    build: ../rweb/fpm-rweb
    image: solsson/fpm-rweb:${PUSH_TAG:-latest}
    entrypoint:
      - echo
      - "This was just a build job. Exiting."

  rweb:
    depends_on:
      - fpm-rweb
    build: ../rweb/rweb
    image: solsson/rweb:${PUSH_TAG:-latest}
    expose:
      - "9000"
    links:
      - rweb-httpd:svn

  rweb-httpd:
    depends_on:
      - svn
    build: ../rweb/httpd
    image: solsson/rweb-httpd:${PUSH_TAG:-latest}
    expose:
      - "80"
    environment:
      ADMIN_REST_ACCESS: "true"
      AUTHN: "anon"

  rwebtest:
    build: ./rwebtest
    labels:
      com.yolean.build-contract: "*"
    environment:
      DEBUG: "true"
    links:
      - rweb-httpd:svn

  svnclient:
    build: ../svnclient
    image: solsson/svnclient:${PUSH_TAG:-latest}

  svntest:
    depends_on:
      - svnclient
    build: ./svntest
    labels:
      com.yolean.build-contract: "*"
    links:
      - svn
      - svn-adminrest

  httpd-curl:
    build: ../httpd
    labels:
      - com.yolean.build-contract
    entrypoint: curl
    command: [-I, "https://svn.apache.org/repos/asf/subversion/trunk/", "-k"]

  httpd-svn-client:
    build: ../httpd
    labels:
      - com.yolean.build-contract
    entrypoint: svn
    command: [info, "https://svn.apache.org/repos/asf/subversion/trunk/", "--trust-server-cert"]
