version: '2'
services:
  # Testing: curl http://$(docker-compose port svn 80)/admin/repocreate -d reponame=test
  svn:
    build: ../httpd
    volumes:
    # work around permission issue with crate as www/daemon user when volume isn't mounted
      - ./svn:/svn
    # cgi development without restart
    #  - ../httpd/bin:/usr/local/apache2/admin-cgi/
    environment:
      ADMIN_REST_ACCESS: "true"
    expose:
      - "80"
    # manual testing on curl http://$(docker-compose port svn 80)/svn/
    #ports:
    #  - "80"
  svn_noadminrest:
    build: ../httpd
    expose:
      - "80"
  test1:
    build: ../debian-svnclient
    labels:
      com.yolean.build-contract: "*"
    links:
      - svn
      - svn_noadminrest
    volumes:
      - ./test1:/test1
    entrypoint:
      - /test1/test1.sh
