version: '2'
services:

  rweb-source:
    # Local build
    build: ../../rweb
    # Online build
    # build: ../rweb/current-dist
    image: solsson/rweb-source:${PUSH_TAG:-latest}

  svn:
    build: ../httpd
    image: solsson/svn-httpd:${PUSH_TAG:-latest}
    expose:
      - "80"

  svn-adminrest:
    build: ../httpd
    environment:
      ADMIN_REST_ACCESS: "true"
    expose:
      - "80"

  svn-authz:
    build: ../httpd
    environment:
      ADMIN_REST_ACCESS: "true"
      AUTHZ: "admrepo"
    expose:
      - "80"

  php-svn:
    build:
      context: ../rweb/fpm-svn
      args:
        PUSH_TAG: ${PUSH_TAG:-latest}
    image: solsson/fpm-svn:${PUSH_TAG:-latest}
    entrypoint:
      - echo
      - "This was just a build job. Exiting."

  php-svn-rweb:
    depends_on:
      - php-svn
    build:
      context: ../rweb/fpm-rweb
      args:
        PUSH_TAG: ${PUSH_TAG:-latest}
    image: solsson/fpm-rweb:${PUSH_TAG:-latest}
    entrypoint:
      - echo
      - "This was just a build job. Exiting."

  rweb-fpm:
    depends_on:
      - php-svn-rweb
      - rweb-source
    build:
      context: ../rweb/rweb
      args:
        PUSH_TAG: ${PUSH_TAG:-latest}
    image: solsson/rweb-fpm:${PUSH_TAG:-latest}
    expose:
      - "9000"
    links:
      - rweb-httpd:svn

  rweb-httpd:
    depends_on:
      - svn
      - rweb-source
    build:
      context: ../rweb/httpd
      args:
        PUSH_TAG: ${PUSH_TAG:-latest}
    image: solsson/rweb-httpd:${PUSH_TAG:-latest}
    expose:
      - "80"
    environment:
      ADMIN_REST_ACCESS: "true"
      AUTHN: "anon"

  rwebtest:
    build: ./rwebtest
    labels:
      com.yolean.build-contract: "*"
    environment:
      DEBUG: "true"
    links:
      - rweb-httpd:svn

  svnclient:
    build: ../svnclient
    image: solsson/svnclient:${PUSH_TAG:-latest}

  svntest:
    depends_on:
      - svnclient
    build:
      context: ./svntest
      args:
        PUSH_TAG: ${PUSH_TAG:-latest}
    labels:
      com.yolean.build-contract: "*"
    links:
      - svn
      - svn-adminrest

  httpd-curl:
    build: ../httpd
    labels:
      - com.yolean.build-contract
    entrypoint: curl
    command: [-I, "https://svn.apache.org/repos/asf/subversion/trunk/", "-k"]

  httpd-svn-client:
    build: ../httpd
    labels:
      - com.yolean.build-contract
    entrypoint: svn
    command: [info, "https://svn.apache.org/repos/asf/subversion/trunk/", "--trust-server-cert"]
