version: '2'
services:
  # Testing: curl http://$(docker-compose port svn 80)/admin/repocreate -d reponame=test
  svn:
    build: ../httpd
    environment:
      ADMIN_REST_ACCESS: "true"
    expose:
      - "80"
    # manual testing on curl http://$(docker-compose port svn 80)/svn/
    #ports:
    #  - "80"
  svn_noadminrest:
    build: ../httpd
    expose:
      - "80"
  debian-svnclient:
    build: ../debian-svnclient
    image: debian-svnclient
  test1:
    depends_on:
      - debian-svnclient
    build: ./test1
    labels:
      com.yolean.build-contract: "*"
    links:
      - svn
      - svn_noadminrest
