devhelp:
  # docker-compose up -d && docker exec -ti dockersvn_devhelp_1 /bin/sh
  # # /src/svnsync/bin/reposync http://svnmaster/svn/r1 http://svnbackup/svn/r1
  image: solsson/alpine-svnclient
  volumes:
   - .:/src
  links:
   - svnmaster
   - svnbackup
  command:
   - /src/svnsync/bin/reposync
svnmaster:
  build: ./httpd
  ports:
   - 80
svnbackup:
  build: ./httpd
  ports:
   - 80
svnsync:
  build: ./svnsync
  links:
   - svnmaster
   - svnbackup
  command:
   - "http://svnmaster/svn/r1"
   - "http://svnbackup/svn/r1"
svnservice:
  # more work needed on this one
  image: solsson/nginx-ssl-proxy
  links:
   - svnmaster
